apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-flask-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-flask-app
  template:
    metadata:
      labels:
        app: my-flask-app
    spec:
      containers:
        - name: my-flask-container
          image: 982534379850.dkr.ecr.ap-south-1.amazonaws.com/my_monitoring_app_image
          ports:
            - containerPort: 5000
